"use client";
import React from 'react';
import Image from 'next/image';

// Attempt to load the manifest generated by optimize-assets
let manifest = {};
try {
  manifest = require('../../public/assets/manifest.json');
} catch (e) {
  // Manifest not available yet, will fallback gracefully
}

/**
 * Helper to clean Turbopack/Webpack hashes from filenames
 * FILENAME.HASH.EXT -> FILENAME.EXT
 */
const cleanBasename = (pathStr) => {
  if (!pathStr) return '';
  const parts = pathStr.split(/[/\\]/);
  const basename = parts.pop();
  const match = basename.match(/^(.+?)\.([a-f0-9]{8,}|[a-f0-9]{32})\.(\w+)$/);
  if (match) return `${match[1]}.${match[3]}`;
  return basename;
};

const getNoExt = (basename) => basename.split('.').slice(0, -1).join('.');

const normalizePath = (pathStr) => {
  if (typeof pathStr !== 'string') return pathStr;
  if (pathStr.startsWith('/../')) return pathStr.substring(3);
  // Ensure it starts with / if it's a relative path from public
  if (!pathStr.startsWith('/') && !pathStr.startsWith('http')) return `/${pathStr}`;
  return pathStr;
};

/**
 * SmartImage Component
 * 
 * Replaces standard <img> and next/image usage across the application.
 * Integrates `optimize-assets` responsive capabilities seamlessly.
 * 
 * Modes:
 * - "dimensions": Shows a debug box with width, height, and safe area.
 * - "placeholder": Shows a graphical mountain placeholder (default).
 * - "image": Renders the actual image (using next/image or native img with generated srcset).
 * 
 * @param {Object} props
 * @param {string|object} props.src - The source URL or static import object.
 * @param {string} [props.mobileSrc] - Optional image source for mobile devices (<768px).
 * @param {string} [props.tabletSrc] - Optional image source for tablet devices (768px - 1024px).
 * @param {string} [props.alt] - The alternative text for the image.
 * @param {number} props.width - The width of the image.
 * @param {number} props.height - The height of the image.
 * @param {string} [props.description] - Description used in dimensions mode.
 * @param {string} [props.className] - Additional Tailwind classes.
 * @param {'dimensions' | 'placeholder' | 'image'} [props.mode='placeholder'] - The render mode.
 * @returns {JSX.Element}
 */
export default function SmartImage({
  src,
  mobileSrc,
  tabletSrc,
  alt,
  width,
  height,
  safeAreaHeight,
  safeAreaWidth,
  displayHeight,
  displayWidth,
  description,
  className = '',
  mode = 'image',
  optimize = true,
  ...props
}) {
  const [hasError, setHasError] = React.useState(false);
  const currentMode = hasError ? 'placeholder' : (process.env.NEXT_PUBLIC_IMAGE_MODE || mode);

  // Resolve src if it's a static import object
  const rawSrc = typeof src === 'object' && src !== null ? src.src : src;
  const imgWidth = typeof src === 'object' && src !== null ? src.width : width;
  const imgHeight = typeof src === 'object' && src !== null ? src.height : height;

  if (currentMode === 'dimensions') {
    safeAreaWidth = safeAreaWidth || (imgWidth ? Math.round(imgWidth * 0.9) : 0);
    safeAreaHeight = safeAreaHeight || (imgHeight ? Math.round(imgHeight * 0.9) : 0);

    return (
      <div
        className={`relative flex flex-col items-center justify-center bg-gray-100 border-2 border-dashed border-gray-300 text-gray-500 overflow-hidden p-4 text-center ${className}`}
        style={{ width: imgWidth ? `${imgWidth}px` : '100%', height: imgHeight ? `${imgHeight}px` : '100%' }}
      >
        <div className="text-sm font-semibold text-gray-700">
          {displayWidth || imgWidth}x{displayHeight || imgHeight} (Safe: {safeAreaWidth}x{safeAreaHeight})
        </div>
        <div className="text-xs font-mono bg-white px-2 py-1 rounded shadow-sm break-all mt-2">
          {rawSrc || 'No src'}
        </div>
        <div className="text-xs font-medium text-gray-600 mt-2">
          Alt: {alt || 'MISSING'}
        </div>
        {description && (
          <div className="text-xs text-gray-500 mt-2 italic max-w-full px-2">
            {description}
          </div>
        )}
      </div>
    );
  }
  if (currentMode === 'placeholder') {
    const w = imgWidth || 400;
    const h = imgHeight || 300;

    // Scale icon elements relative to size so small thumbnails and huge
    // banners both get proportionate mountains/sun instead of a stretched
    // fixed 200x150 illustration.
    const vbW = 200;
    const vbH = Math.max(60, Math.round((h / w) * vbW)); // preserve aspect ratio in viewBox space
    const sunR = Math.max(6, Math.round(vbW * 0.06));
    const sunCx = Math.round(vbW * 0.25);
    const sunCy = Math.round(vbH * 0.3);

    const fillStyle = props.fill
      ? {
          position: 'absolute',
          height: '100%',
          width: '100%',
          left: 0,
          top: 0,
          right: 0,
          bottom: 0,
        }
      : { width: imgWidth ? `${imgWidth}px` : '100%', height: imgHeight ? `${imgHeight}px` : '100%' };

    return (
      <div
        className={`flex items-center justify-center bg-[#D0D6DC] overflow-hidden ${props.fill ? '' : 'relative'} ${className}`}
        style={fillStyle}
      >
        <svg
          viewBox={`0 0 ${vbW} ${vbH}`}
          preserveAspectRatio="xMidYMid slice"
          className="w-full h-full text-[#EDF1F5]"
          fill="currentColor"
          xmlns="http://www.w3.org/2000/svg"
        >
          <circle cx={sunCx} cy={sunCy} r={sunR} />
          <path
            d={`M-20 ${vbH} C ${vbW * 0.05} ${vbH * 0.67} ${vbW * 0.2} ${vbH * 0.53} ${vbW * 0.35} ${vbH * 0.8} C ${vbW * 0.425} ${vbH * 0.93} ${vbW * 0.475} ${vbH} ${vbW * 0.55} ${vbH} L -20 ${vbH} Z`}
          />
          <path
            d={`M${vbW * 0.25} ${vbH} C ${vbW * 0.45} ${vbH * 0.53} ${vbW * 0.65} ${vbH * 0.2} ${vbW * 0.85} ${vbH * 0.67} C ${vbW * 0.95} ${vbH * 0.9} ${vbW * 1.05} ${vbH} ${vbW * 1.15} ${vbH} L ${vbW * 0.25} ${vbH} Z`}
          />
        </svg>
      </div>
    );
  }

  if (!rawSrc) return null;

  // --- Responsive Image manifest lookup logic ---
  const srcString = decodeURIComponent(rawSrc);
  let imageVariants = null;

  // Only attempt manifest lookup if optimization is enabled
  if (optimize) {
    // 1. Direct match
    if (manifest[srcString]) {
      imageVariants = manifest[srcString];
    } else {
      const lookupBasename = cleanBasename(srcString);
      const lookupNoExt = getNoExt(lookupBasename);

      // 2. Fuzzy match by basename
      let keyMatch = Object.keys(manifest).find(
        (key) => cleanBasename(key) === lookupBasename
      );

      // 3. Match by name only (handles extension changes)
      if (!keyMatch) {
        keyMatch = Object.keys(manifest).find(
          (key) => getNoExt(cleanBasename(key)) === lookupNoExt
        );
      }

      imageVariants = keyMatch ? manifest[keyMatch] : null;
    }
  }

  // If we found variants in the manifest, we construct our own responsive <img> wrapper
  if (imageVariants) {
    const widths = Object.keys(imageVariants)
      .filter(k => k !== 'original')
      .sort((a, b) => Number(a) - Number(b));

    const srcSetEntries = widths.map(w => `${encodeURI(normalizePath(imageVariants[w]))} ${w}w`);

    if (imgWidth && imageVariants.original) {
      srcSetEntries.push(`${encodeURI(normalizePath(imageVariants.original))} ${imgWidth}w`);
    }

    const srcSet = srcSetEntries.length > 0 ? srcSetEntries.join(', ') : undefined;
    const defaultSrc = encodeURI(normalizePath(imageVariants.original || imageVariants[widths[widths.length - 1]] || rawSrc));
    const sizes = props.fill ? (props.sizes || "100vw") : props.sizes;
    const { fill, style: customStyle, priority, loading, ...restProps } = props;

    const fillStyle = fill
      ? {
        position: 'absolute',
        height: '100%',
        width: '100%',
        left: 0,
        top: 0,
        right: 0,
        bottom: 0,
        color: 'transparent',
      }
      : {};

    const combinedStyle = { ...fillStyle, ...customStyle };

    const nativeImg = (
      <img
        src={defaultSrc}
        srcSet={srcSet}
        sizes={srcSet ? sizes : undefined}
        width={fill ? undefined : imgWidth}
        height={fill ? undefined : imgHeight}
        alt={alt || ''}
        className={className}
        loading={priority ? undefined : (loading || "lazy")}
        fetchPriority={priority ? "high" : undefined}
        style={Object.keys(combinedStyle).length > 0 ? combinedStyle : undefined}
        onError={() => setHasError(true)}
        {...restProps}
      />
    );

    if (mobileSrc || tabletSrc) {
      return (
        <picture className={`block ${className}`}>
          {mobileSrc && <source media="(max-width: 767px)" srcSet={mobileSrc} />}
          {tabletSrc && <source media="(min-width: 768px) and (max-width: 1023px)" srcSet={tabletSrc} />}
          {nativeImg}
        </picture>
      );
    }

    return nativeImg;
  }

  // Fallback to Next.js Image if no manifest variant is found (e.g. external images, unoptimized SVGs, or optimize={false})
  const nextImage = (
    <Image
      src={src}
      alt={alt || ''}
      width={imgWidth}
      height={imgHeight}
      className={className}
      sizes={props.fill ? (props.sizes || "100vw") : props.sizes}
      onError={() => setHasError(true)}
      {...props}
    />
  );

  if (mobileSrc || tabletSrc) {
    return (
      <picture className={`block ${className}`}>
        {mobileSrc && <source media="(max-width: 767px)" srcSet={mobileSrc} />}
        {tabletSrc && <source media="(min-width: 768px) and (max-width: 1023px)" srcSet={tabletSrc} />}
        {nextImage}
      </picture>
    );
  }

  return nextImage;
}
